/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SizeInfo = IDL.Record({
  'height' : IDL.Nat,
  'length' : IDL.Nat,
  'units' : IDL.Text,
  'width' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const QuotationRequest = IDL.Record({
  'requester' : IDL.Principal,
  'additionalNotes' : IDL.Text,
  'contactPerson' : IDL.Text,
  'siteAddress' : IDL.Text,
  'email' : IDL.Text,
  'siteType' : IDL.Text,
  'timestamp' : Time,
  'companyName' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'sizeInfo' : IDL.Vec(SizeInfo),
});
export const ProfileType = IDL.Variant({
  'dealer' : IDL.Null,
  'company' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'dealerContactNumber' : IDL.Opt(IDL.Text),
  'dealerLocation' : IDL.Opt(IDL.Text),
  'companyAddress' : IDL.Opt(IDL.Text),
  'profileType' : ProfileType,
  'companyRegistrationNumber' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuotationRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(SizeInfo),
        IDL.Text,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllQuotationRequests' : IDL.Func(
      [],
      [IDL.Vec(QuotationRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getDealerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getRequestsByRequester' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(QuotationRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCompanyProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveDealerProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SizeInfo = IDL.Record({
    'height' : IDL.Nat,
    'length' : IDL.Nat,
    'units' : IDL.Text,
    'width' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const QuotationRequest = IDL.Record({
    'requester' : IDL.Principal,
    'additionalNotes' : IDL.Text,
    'contactPerson' : IDL.Text,
    'siteAddress' : IDL.Text,
    'email' : IDL.Text,
    'siteType' : IDL.Text,
    'timestamp' : Time,
    'companyName' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'sizeInfo' : IDL.Vec(SizeInfo),
  });
  const ProfileType = IDL.Variant({
    'dealer' : IDL.Null,
    'company' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'dealerContactNumber' : IDL.Opt(IDL.Text),
    'dealerLocation' : IDL.Opt(IDL.Text),
    'companyAddress' : IDL.Opt(IDL.Text),
    'profileType' : ProfileType,
    'companyRegistrationNumber' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuotationRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(SizeInfo),
          IDL.Text,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllQuotationRequests' : IDL.Func(
        [],
        [IDL.Vec(QuotationRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getDealerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getRequestsByRequester' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(QuotationRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCompanyProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveDealerProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };