/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ProfileType = { 'dealer' : null } |
  { 'company' : null };
export interface QuotationRequest {
  'requester' : Principal,
  'additionalNotes' : string,
  'contactPerson' : string,
  'siteAddress' : string,
  'email' : string,
  'siteType' : string,
  'timestamp' : Time,
  'companyName' : string,
  'phoneNumber' : string,
  'sizeInfo' : Array<SizeInfo>,
}
export interface SizeInfo {
  'height' : bigint,
  'length' : bigint,
  'units' : string,
  'width' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'dealerContactNumber' : [] | [string],
  'dealerLocation' : [] | [string],
  'companyAddress' : [] | [string],
  'profileType' : ProfileType,
  'companyRegistrationNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuotationRequest' : ActorMethod<
    [string, string, string, string, string, string, Array<SizeInfo>, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllQuotationRequests' : ActorMethod<[], Array<QuotationRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getDealerProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getRequestsByRequester' : ActorMethod<[Principal], Array<QuotationRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCompanyProfile' : ActorMethod<[string, string, string], undefined>,
  'saveDealerProfile' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];